"""Generate deterministic Gmsh GEO source around CAD exchange files."""

from __future__ import annotations

from pathlib import Path
from typing import Mapping

from microfluidics.cad.config import (
    BoundaryBoxSelector,
    CadMeshConfig,
    CadParameters,
)


def procedural_boundary_selectors(
    params: CadParameters,
) -> dict[str, BoundaryBoxSelector]:
    params.validate()
    scale = max(
        params.inlet_length,
        params.outlet_length,
        params.channel_height,
        params.inlet_width,
        params.outlet_width,
    )
    # STEP/BREP import applies OCCT entity tolerances (commonly around 1e-7 m).
    # The box must contain the complete imported terminal face, including that
    # tolerance, while adjacent wall faces still extend far outside the box.
    eps = max(scale * 1e-5, 1e-7)
    return {
        "left_inlet": BoundaryBoxSelector(
            (
                -params.inlet_length - eps,
                -0.5 * params.inlet_width - eps,
                -eps,
                -params.inlet_length + eps,
                0.5 * params.inlet_width + eps,
                params.channel_height + eps,
            )
        ),
        "right_inlet": BoundaryBoxSelector(
            (
                params.inlet_length - eps,
                -0.5 * params.inlet_width - eps,
                -eps,
                params.inlet_length + eps,
                0.5 * params.inlet_width + eps,
                params.channel_height + eps,
            )
        ),
        "outlet": BoundaryBoxSelector(
            (
                -0.5 * params.outlet_width - eps,
                params.outlet_length - eps,
                -eps,
                0.5 * params.outlet_width + eps,
                params.outlet_length + eps,
                params.channel_height + eps,
            )
        ),
    }


def _numbers(bounds: tuple[float, ...]) -> str:
    return ", ".join(f"{value:.17g}" for value in bounds)


def build_geo_source(
    *,
    cad_file_name: str,
    boundary_selectors: Mapping[str, BoundaryBoxSelector],
    mesh: CadMeshConfig,
) -> str:
    """Build GEO that imports one CAD solid and assigns its physical groups."""

    mesh.validate()
    expected = {"left_inlet", "right_inlet", "outlet"}
    if set(boundary_selectors) != expected:
        raise ValueError(f"boundary selectors must define exactly {sorted(expected)}")
    if Path(cad_file_name).name != cad_file_name:
        raise ValueError("cad_file_name must be a file name relative to the GEO file")
    for name, selector in boundary_selectors.items():
        selector.validate(name)

    variables = {
        "left_inlet": "leftInlet",
        "right_inlet": "rightInlet",
        "outlet": "outlet",
    }
    lines = [
        "// Generated by microfluidics.cad; edit the JSON/YAML source, not this file.",
        'SetFactory("OpenCASCADE");',
        f'fluid() = ShapeFromFile("{cad_file_name}");',
        "If (#fluid() != 1)",
        '  Error("CAD source must contain exactly one fluid volume");',
        "EndIf",
        "allBoundary() = CombinedBoundary{ Volume{fluid()}; };",
    ]
    for physical_name in ("left_inlet", "right_inlet", "outlet"):
        variable = variables[physical_name]
        lines.extend(
            (
                f"{variable}() = Surface In BoundingBox"
                f"{{{_numbers(boundary_selectors[physical_name].bounds)}}};",
                f"If (#{variable}() != 1)",
                f'  Error("Expected exactly one {physical_name} surface");',
                "EndIf",
            )
        )
    lines.extend(
        (
            "walls() = allBoundary();",
            "walls() -= {leftInlet(), rightInlet(), outlet()};",
            "If (#walls() == 0)",
            '  Error("No wall surfaces remain after terminal classification");',
            "EndIf",
            'Physical Volume("fluid", 1) = {fluid()};',
            'Physical Surface("left_inlet", 2) = {leftInlet()};',
            'Physical Surface("right_inlet", 3) = {rightInlet()};',
            'Physical Surface("outlet", 4) = {outlet()};',
            'Physical Surface("walls", 5) = {walls()};',
            f"Mesh.MeshSizeMin = {mesh.element_size:.17g};",
            f"Mesh.MeshSizeMax = {mesh.element_size:.17g};",
            "Mesh.MeshSizeFromPoints = 0;",
            "Mesh.MeshSizeFromCurvature = 0;",
            "Mesh.MeshSizeExtendFromBoundary = 0;",
            "Mesh.MshFileVersion = 4.1;",
            "Mesh.Binary = 1;",
            "Mesh.SaveAll = 0;",
            "",
        )
    )
    return "\n".join(lines)


__all__ = ["build_geo_source", "procedural_boundary_selectors"]
